// @generated by protoc-gen-es v1.9.0 with parameter "target=ts,import_extension=.ts"
// @generated from file event/chat/v1/event.proto (package event.chat.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum event.chat.v1.Event
 */
export enum Event {
  /**
   * @generated from enum value: EVENT_SOCKET_JOIN_MEETING = 0;
   */
  SOCKET_JOIN_MEETING = 0,
}
// Retrieve enum metadata with: proto3.getEnumType(Event)
proto3.util.setEnumType(Event, "event.chat.v1.Event", [
  { no: 0, name: "EVENT_SOCKET_JOIN_MEETING" },
]);

