environment: D
server:
  grpc:
    host: 0.0.0.0
    port: 10000
  http:
    host: 0.0.0.0
    port: 9000
  worker:
    port: 9000

service_name: iam_service

postgresql:
  host: localhost
  port: 5432
  database: chat-service
  username: postgres
  password: dev-test
  sslmode: disable
  sslrootcert:
  search_path: public
  rds:
    is_enabled: false
    region: ap-southeast-1
