// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file api/chat/v1/chat.proto (package api.chat.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { UserCreateMeetingRequest, UserCreateMeetingResponse, UserJoinMeetingRequest, UserJoinMeetingResponse } from "./chat_pb.ts";

/**
 * @generated from rpc api.chat.v1.ChatAPI.UserCreateMeeting
 */
export const userCreateMeeting = {
  localName: "userCreateMeeting",
  name: "UserCreateMeeting",
  kind: MethodKind.Unary,
  I: UserCreateMeetingRequest,
  O: UserCreateMeetingResponse,
  service: {
    typeName: "api.chat.v1.ChatAPI"
  }
} as const;

/**
 * rpc TestAPI(TestAPIRequest) returns (TestAPIResponse) {} // POST
 * rpc GetMeeting(GetMeetingRequest) returns (GetMeetingResponse) {
 *     option idempotency_level = NO_SIDE_EFFECTS;
 * }
 *
 * @generated from rpc api.chat.v1.ChatAPI.UserJoinMeeting
 */
export const userJoinMeeting = {
  localName: "userJoinMeeting",
  name: "UserJoinMeeting",
  kind: MethodKind.Unary,
  I: UserJoinMeetingRequest,
  O: UserJoinMeetingResponse,
  service: {
    typeName: "api.chat.v1.ChatAPI"
  }
} as const;
