// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts,import_extension=.ts"
// @generated from file api/chat/v1/chat.proto (package api.chat.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UserCreateMeetingRequest, UserCreateMeetingResponse, UserJoinMeetingRequest, UserJoinMeetingResponse } from "./chat_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.chat.v1.ChatAPI
 */
export const ChatAPI = {
  typeName: "api.chat.v1.ChatAPI",
  methods: {
    /**
     * @generated from rpc api.chat.v1.ChatAPI.UserCreateMeeting
     */
    userCreateMeeting: {
      name: "UserCreateMeeting",
      I: UserCreateMeetingRequest,
      O: UserCreateMeetingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * rpc TestAPI(TestAPIRequest) returns (TestAPIResponse) {} // POST
     * rpc GetMeeting(GetMeetingRequest) returns (GetMeetingResponse) {
     *     option idempotency_level = NO_SIDE_EFFECTS;
     * }
     *
     * @generated from rpc api.chat.v1.ChatAPI.UserJoinMeeting
     */
    userJoinMeeting: {
      name: "UserJoinMeeting",
      I: UserJoinMeetingRequest,
      O: UserJoinMeetingResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

