// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts,import_extension=.ts"
// @generated from file api/iam/v1/test.proto (package api.iam.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { TestApiGenProtoRequest, TestApiGenProtoResponse } from "./test_pb.ts";

/**
 * @generated from rpc api.iam.v1.SecurityTokenAPI.TestApiGenProto
 */
export const testApiGenProto = {
  localName: "testApiGenProto",
  name: "TestApiGenProto",
  kind: MethodKind.Unary,
  I: TestApiGenProtoRequest,
  O: TestApiGenProtoResponse,
  service: {
    typeName: "api.iam.v1.SecurityTokenAPI"
  }
} as const;
