// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts,import_extension=.ts"
// @generated from file api/iam/v1/test.proto (package api.iam.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { TestApiGenProtoRequest, TestApiGenProtoResponse } from "./test_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.iam.v1.SecurityTokenAPI
 */
export const SecurityTokenAPI = {
  typeName: "api.iam.v1.SecurityTokenAPI",
  methods: {
    /**
     * @generated from rpc api.iam.v1.SecurityTokenAPI.TestApiGenProto
     */
    testApiGenProto: {
      name: "TestApiGenProto",
      I: TestApiGenProtoRequest,
      O: TestApiGenProtoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

