// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/iam/v1/test.proto

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityTokenAPI_TestApiGenProto_FullMethodName = "/api.iam.v1.SecurityTokenAPI/TestApiGenProto"
)

// SecurityTokenAPIClient is the client API for SecurityTokenAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityTokenAPIClient interface {
	TestApiGenProto(ctx context.Context, in *TestApiGenProtoRequest, opts ...grpc.CallOption) (*TestApiGenProtoResponse, error)
}

type securityTokenAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityTokenAPIClient(cc grpc.ClientConnInterface) SecurityTokenAPIClient {
	return &securityTokenAPIClient{cc}
}

func (c *securityTokenAPIClient) TestApiGenProto(ctx context.Context, in *TestApiGenProtoRequest, opts ...grpc.CallOption) (*TestApiGenProtoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestApiGenProtoResponse)
	err := c.cc.Invoke(ctx, SecurityTokenAPI_TestApiGenProto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityTokenAPIServer is the server API for SecurityTokenAPI service.
// All implementations should embed UnimplementedSecurityTokenAPIServer
// for forward compatibility.
type SecurityTokenAPIServer interface {
	TestApiGenProto(context.Context, *TestApiGenProtoRequest) (*TestApiGenProtoResponse, error)
}

// UnimplementedSecurityTokenAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityTokenAPIServer struct{}

func (UnimplementedSecurityTokenAPIServer) TestApiGenProto(context.Context, *TestApiGenProtoRequest) (*TestApiGenProtoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestApiGenProto not implemented")
}
func (UnimplementedSecurityTokenAPIServer) testEmbeddedByValue() {}

// UnsafeSecurityTokenAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityTokenAPIServer will
// result in compilation errors.
type UnsafeSecurityTokenAPIServer interface {
	mustEmbedUnimplementedSecurityTokenAPIServer()
}

func RegisterSecurityTokenAPIServer(s grpc.ServiceRegistrar, srv SecurityTokenAPIServer) {
	// If the following call pancis, it indicates UnimplementedSecurityTokenAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityTokenAPI_ServiceDesc, srv)
}

func _SecurityTokenAPI_TestApiGenProto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestApiGenProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityTokenAPIServer).TestApiGenProto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityTokenAPI_TestApiGenProto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityTokenAPIServer).TestApiGenProto(ctx, req.(*TestApiGenProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityTokenAPI_ServiceDesc is the grpc.ServiceDesc for SecurityTokenAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityTokenAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.iam.v1.SecurityTokenAPI",
	HandlerType: (*SecurityTokenAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestApiGenProto",
			Handler:    _SecurityTokenAPI_TestApiGenProto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/iam/v1/test.proto",
}
